name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.3"
          gleam-version: "1.12.0"
          rebar3-version: "3.24.0"
          elixir-version: "1.18.3"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test
